# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Awkward Python
tagline:             'Still figuring stuff out...'
description:         'A blog about Python, scientific software, life, and statistics'
url:
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Drew O'Kane
  url:
  email:

# Custom vars
version:             1.0.1

# Stuff for Jekyll
gems: [jekyll-paginate]

# Markdown particulars
markdown: kramdown
